### PR TITLE
fix: install extra group  when using pre-commit

### PR DESCRIPTION
**Pull request by jrottenberg**
On fresh install:

```
ERROR: Python requirements are missing: 'ansible-core' not found.
```

### CODE REVIEW

**Review by xoxys — CHANGES_REQUESTED** [review]
Thanks! Good catch. I would prefer to extend https://github.com/thegeeklab/ansible-doctor/blob/main/.pre-commit-hooks.yaml#L8 instead:

```
  ...
  always_run: True
  additional_dependencies:
    - .[ansible-core]
```

This will install the extra group from https://github.com/thegeeklab/ansible-doctor/blob/main/pyproject.toml#L46-L47 by default, while users can still overwrite it to a specific version if required. Could you add this change?

**Comment by rottj006** [comment]
Yep, much nicer that way.

**Comment by jrottenberg** [comment]
Yep, much nicer that way !

**Review by xoxys — APPROVED** [review]

**Comment by xoxys** [comment]
Thanks again!

**Pull request merged**
